/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_nazuha26_WinNativeLib */

#ifndef _Included_io_github_nazuha26_WinNativeLib
#define _Included_io_github_nazuha26_WinNativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    hookWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_hookWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    unhookWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_unhookWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    configureWindow
 * Signature: (Ljava/awt/Component;IIZ)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_configureWindow
  (JNIEnv *, jobject, jobject, jint, jint, jboolean);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    setBackgroundColor
 * Signature: (Ljava/awt/Component;III)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_setBackgroundColor
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    setBorderColor
 * Signature: (Ljava/awt/Component;III)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_setBorderColor
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    getDPIScale
 * Signature: (Ljava/awt/Component;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_github_nazuha26_WinNativeLib_getDPIScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    minimizeWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_minimizeWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    maximizeWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_maximizeWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    restoreWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_restoreWindow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_nazuha26_WinNativeLib
 * Method:    closeWindow
 * Signature: (Ljava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_io_github_nazuha26_WinNativeLib_closeWindow
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
